### ISSUE TITLE
[egui_dnd] Two elements with same content create conflicts

### ISSUE THREAD

**Issue by SpeckyYT** [lucasmerlin/hello_egui#25]
I was implementing egui_dnd for a hotkey system which requires changing the order for precedence.

Here's what it looks like when I don't do anything:
![image](https://github.com/lucasmerlin/hello_egui/assets/40666126/91154e5d-cbe0-45b1-80cf-b9d7afbe7c83)

Here's what it looks like when I try to move one of the two elements with same content:
![image](https://github.com/lucasmerlin/hello_egui/assets/40666126/f9140e6d-60cc-4766-b328-b42bff61acb5)

Also, small unrelated question, is it possible to remove an element with egui_dnd?

**Comment by lucasmerlin** [comment]
Do you have three separate dnd areas? Are they sharing the same ID?

> is it possible to remove an element with egui_dnd? 

Do you mean by dragging it somewhere outside or on a delete area or something like that? Not possible right now, but that would be a nice addition.

**Comment by SpeckyYT** [comment]
> Do you have three separate dnd areas? Are they sharing the same ID?

Sorry for not explaining it well enough. There is only 1 dnd area, where every line uses `ui.horizontal()` and represents a separate value. I do not assign any IDs by myself in code.

The following is the code I wrote:
```rs
// Definitions:
// self.quick_keys == Vec<(egui::Key, usize, usize)> => (key, from, to)

Dnd::new(ui, "dnd_quick_keys").show_vec(&mut self.quick_keys, |ui, (key, from, to), handle, _state| {
    ui.horizontal(|ui| {
        handle.ui(ui, |ui| {
            key_input(ui, key); // uses approx `ui.text_edit_singleline(&mut key.to_string())`
            integer_input(ui, from); // uses `DragValue::new(from)`
            integer_input(ui, to); // uses `DragValue::new(to)`
        });
        if ui.button("-").clicked() {
            // self.quick_keys.remove(state.index);
        }
    });
});
```

I tried to use `ui.push_id((state.index))`, but nothing changes and it still creates conflicts.

```rs
Dnd::new(ui, "dnd_quick_keys").show_vec(&mut self.quick_keys, |ui, (key, from, to), handle, _state| {
    ui.push_id((*key, *from, *to, _state.index), |ui| {
      // ui horizontal, handle ui, etc
    });
});
```

I also tried to change the content entirely depending if you drag it or not, but still nothing, still conflicts

```rs
if state.dragged {
    ui.label(format!("{:?}", key));
} else {
    key_input(ui, key);
    integer_input(ui, from);
    integer_input(ui, to);
    if ui.button("-").clicked() {
        // self.quick_keys.remove(state.index);
    }
}
```

I also tried to remove the `ui.horizontal` entirely, but no, still conflicts.

Not sure if I'm doing something wrong.

Here's the video of what happens when two elements are the same:

https://github.com/lucasmerlin/hello_egui/assets/40666126/5bc683b3-ef35-4c94-9163-7c975174c0ec

And here's what happens if they aren't equal anymore:

https://github.com/lucasmerlin/hello_egui/assets/40666126/ffb2f8aa-c269-4f73-8fc1-c0c9ed967531

> Do you mean by dragging it somewhere outside or on a delete area or something like that?

I was simply thinking of a button to remove it, but I don't think that's possible because the vector is already taken as a `&mut [T]` reference, so I can't simply remove it inside of the dnd. I guess I'll have to try to find a different solution for it.

**Comment by SpeckyYT** [comment]
Is there any reason why the values are forced to be unique? I thought that this crate would store the index by itself behind the scenes, so that it never conflicts.

**Comment by lucasmerlin** [comment]
> Is there any reason why the values are forced to be unique? I thought that this crate would store the index by itself behind the scenes, so that it never conflicts.

In the beginning I tried to work with the index only but it turned out too fragile. When the list order changes or a item is inserted (maybe because a update was received from the server) while the user is dragging, the currently dragged item would suddenly change.

**Comment by SpeckyYT** [comment]
Ok, I fixed the issue by not allowing duplicates. For me this issue is completed, but if you want, you can close it now, or whenever you update the documentation. Thanks for the help.
