### ISSUE TITLE
add

### ISSUE THREAD

**Issue by rust-ferrum** [lucasmerlin/hello_egui#31]
please add mobile version

**Comment by lucasmerlin** [comment]
Hi! The hello_egui crates should all work fine on mobile

**Comment by rust-ferrum** [comment]
![Скриншот сделанный 2024-07-18 в 13 15 24](https://github.com/user-attachments/assets/ace24f56-9d25-4a60-815a-f80e18ac9efc)

**Comment by lucasmerlin** [comment]
Ah, what kind of phone is that?

**Comment by rust-ferrum** [comment]
firefox Responsive Design Mode

**Comment by rust-ferrum** [comment]
the problem is in Firefox Responsive Design Mode?

**Comment by lucasmerlin** [comment]
From the screenshot it looks like you made the screen very small, then of course not everything is going to fit. It does look fine on my phone, and I think it is good enough for a example app. If you want you can open a pr to automatically lower the font size when the screen is very small.
