### ISSUE TITLE
egui_thumbhash Freezing while image loading

### ISSUE THREAD

**Issue by CodedNil** [lucasmerlin/hello_egui#33]
Apologies if the issue is with egui not your crate, I'm unsure currently.
I mostly copied the thumbhash example code for my project, and it works mostly and renders the thumbhash before loading the image, but while an image is being loaded the entire app freezes, as if its not loading asynchronously in another thread, any ideas how to fix this?

```rust
// Only render images if they are visible (this is basically lazy loading)
let image_size = Vec2::new(width, height);
let image_rect = if ui
    .is_rect_visible(Rect::from_min_size(ui.next_widget_position(), image_size))
{
    let image = egui::Image::new(format!("http://{}/wallpapers/{}", self.host, file_name))
        .show_loading_spinner(false);
    ui.add_sized(
        image_size,
        ThumbhashImage::new(image, &wallpaper.thumbhash).rounding(16.0),
    )
    .rect
} else {
    let (rect, _) = ui.allocate_exact_size(image_size, Sense::hover());
    rect
};
```

**Comment by lucasmerlin** [comment]
Hi! 
I assume your app also freezes when not using the thumbhash image?

Egui's image loading is not very optimized right now, pretty sure the images are decoded on the ui thread, so decoding big images will cause very noticable lag. 

On wasm the best thing would be to let the browser load and decode the image via a ImageBitmap and pass it to wgpu via [copy_texture_to_texture](https://docs.rs/wgpu/latest/wgpu/struct.CommandEncoder.html#method.copy_texture_to_texture)

In my app I build a custom image loader that loads images on a different thread natively and uses the ImageBitmap in the browser and image loading is really smooth, even if you quickly scroll through a list of high res images. It's not open source but I could add it as a crate to this repo if you're interested.

**Comment by CodedNil** [comment]
That's perfect thank you, I just assumed it was freezing while downloading the image but it being while decoding makes a lot of sense and has helped solve this by pushing that to another thread.
