### ISSUE TITLE
correct way of nesting flexes

### ISSUE THREAD

**Issue by Pentalimbed** [lucasmerlin/hello_egui#45]
I'm trying to create a pane/docking system with egui_flex 0.1.1. What I'm trying to achieve is:
- a group of outer flexes that determines the layout of the panes
- each pane will display its content, which may use its own flexes but shouldn't affect the size of the panes

Here is a sample of my code:
```rust
Flex::vertical().show(ui, |flex| {
    flex.add_flex(egui_flex::item().grow(0.4), Flex::horizontal(), |flex| {
        flex.add_simple(egui_flex::item().grow(0.3), |ui| {
            self.ui_pane(ui, PaneContent::Empty);
        });
        flex.add_widget(egui_flex::item(), Separator::default().vertical());
        flex.add_simple(egui_flex::item().grow(0.7), |ui| {
            self.ui_pane(ui, PaneContent::Empty);
        });
    });
    flex.add_widget(egui_flex::item(), Separator::default().horizontal());
    flex.add_simple(egui_flex::item().grow(0.6), |ui| {
        self.ui_pane(ui, PaneContent::Empty);
    });
});
```

For some reason the contents keep stretching beyond the boundary of the window itself. I can't figure out what I did wrong just by looking at the examples. I'd appreciate any help.

**Comment by lucasmerlin** [comment]
grow(0.4) will just mean that if there is more space available than needed this item will grow with a factor of 0.4 and the other one with a factor of 0.6. If you want to use this for relative spacing you could give the items a basis of 0, I think then it should work as expected.

**Comment by Pentalimbed** [comment]
Thank you! It worked...for a flash second, and then the executable crashes:
> thread 'main' panicked at D:\ProgramData\rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.29.1\src\ui.rs:897:9:
assertion failed: 0.0 <= width

Though for that instant it does look like things are arranged correctly. Here is the updated code:
```rust
Flex::vertical().show(ui, |flex| {
    flex.add_flex(
        egui_flex::item().grow(0.4).basis(0.0),
        Flex::horizontal(),
        |flex| {
            flex.add_simple(egui_flex::item().grow(0.3).basis(0.0), |ui| {
                self.ui_pane(ui, PaneContent::Empty);
            });
            flex.add_widget(egui_flex::item(), Separator::default().vertical());
            flex.add_simple(egui_flex::item().grow(0.7).basis(0.0), |ui| {
                self.ui_pane(ui, PaneContent::Empty);
            });
        },
    );
    flex.add_widget(egui_flex::item(), Separator::default().horizontal());
    flex.add_simple(egui_flex::item().grow(0.6).basis(0.0), |ui| {
        self.ui_pane(ui, PaneContent::Empty);
    });
});
```
